import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  res.statusCode = 302;
  res.setHeader("Location", "/components/button");

  return {
    props: {}
  };
};

export default Home;
