import type { NextPage } from "next";
import Head from "next/head";
import type { CSSProperties } from "react";
import { useState } from "react";

import * as Component from "../../components/partial/Component";

const ComponentModal: NextPage = () => {
  /* order - state */
  // 너비
  const [width, setWidth] = useState(100);
  /* order - variable */
  // preview style
  const modalStyle: CSSProperties = {};
  /* handler */
  const handleExport = () => {};

  return (
    <>
      <Head>
        <title>Components - Modal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component.Container>
        <Component.Section>
          <Component.Header>Preview</Component.Header>
          <Component.Scrollable></Component.Scrollable>
        </Component.Section>

        <Component.Aside>
          <Component.Header>Option</Component.Header>
        </Component.Aside>
      </Component.Container>
    </>
  );
};

export default ComponentModal;
